from django.contrib import admin
from main.models import *

# Register your models here.
admin.site.register(language_info)
admin.site.register(basic_base)
admin.site.register(note_info)
admin.site.register(interest_skill_info)
admin.site.register(industry_info)
admin.site.register(company_info)
admin.site.register(position_info)
admin.site.register(country_info)
admin.site.register(states_info)
admin.site.register(cities_info)
admin.site.register(location_info)
admin.site.register(location_item_name_info)
admin.site.register(school_info)
admin.site.register(concentration_info)
admin.site.register(degree_info)
admin.site.register(phone_item_name_info)
admin.site.register(email_item_name_info)
admin.site.register(sn_item_name_info)
admin.site.register(phone_number_info)
admin.site.register(email_info)
admin.site.register(sn_info)
admin.site.register(has_phone_number_info)
admin.site.register(has_email_info)
admin.site.register(has_sn_info)
admin.site.register(has_interest_skill)
admin.site.register(has_note)
admin.site.register(work_for)
admin.site.register(go_location)
admin.site.register(we_meet)
admin.site.register(has_edu)